### ISSUE TITLE
No more roadmap?

### ISSUE THREAD

**Issue by NOhs** [boostorg/website#207]
I am not sure if this is the correct place, but I was wondering if boost will have a roadmap (like it used to have [svn.boost.org - roadmap](https://svn.boost.org/trac/boost/roadmap)) on git now, or somewhere on their website, with estimates on when new versions are coming out.

**Comment by danieljames** [comment]
No, I don't think anyone paid much attention to that any way. Especially since there are still a lot of open tickets with past milestones. You can see the release schedule on the calendar on the website's [development page](http://www.boost.org/development/). Although we're often a little behind.
