### ISSUE TITLE
test targets minimal/full should be removed from the documentation

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website#259]
They are unimplemented and misleading. I will submit a pull request.

**Comment by danieljames** [comment]
What is this referring to? Maybe a link would help.

**Comment by vinniefalco** [comment]
http://www.boost.org/development/requirements.html

```
test-suite minimal : [ run a.cpp ] ;
test-suite full : minimal [ compile b.cpp ] ;
test-suite extra : [ run c.cpp ] ;
```

This was never implemented, and it looks like it will never be implemented. I'm getting more information from Rene.

**Comment by jeking3** [comment]
@vinniefalco reminder to make a pull request for this

**Comment by vinniefalco** [comment]
@pdimov Agrees this should be changed but I am unsure what the right wording is

**Comment by pdimov** [comment]
@danieljames is `requirements.html` the right file to edit, or does it have a source?

**Comment by pdimov** [comment]
Maybe something like https://github.com/boostorg/website/pull/277
