### ISSUE TITLE
Repository file material is too aggressively cached

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website#262]
Files served from the website which originate from submodules should have a shorter cache expiration. For example:
http://www.boost.org/doc/libs/develop/libs/beast/doc/html/

I believe these files have no cache expiration, or an expiration far into the future. We need the opposite, especially for **develop**, they should have a very short cache or not be cached at all. I think this is a setting for the HTTP headers.

**Comment by danieljames** [comment]
The develop/master documentation has an expiration of 1 day.  I'll make it shorter, but the turnaround for documentation is at least a few hours, sometimes more, so there will be a delay regardless.

**Comment by vinniefalco** [comment]
Oh.. one day is not so bad. I thought it was "never."
