### ISSUE TITLE
Condensed listing of all libraries

### ISSUE THREAD

**Issue by eldiener** [boostorg/website#296]
Besides the "All | Categorized | Standard Proposals | TR1 libraries" views of libraries for any given release I would like to see a Condensed listing of all libraries which matched the "Libraries Listed Alphabetically" for each actual Boost distribution. This would enable the quick finding of any individual library's documentation from the online website. Right now with the "All" listing you have to scroll through many pages to find the library in which you are interested. The idea would be to change "All | Categorized | Standard Proposals | TR1 libraries" to "All | Categorized | Condensed | Standard Proposals | TR1 libraries" and the Condensed tab would then match how the "Libraries Listed Alphabetically" are displayed.

I would submit a PR for this but figuring out how this gets generated is beyond my efforts.

**Comment by danieljames** [comment]
I had a quick go at implementing that on the beta site:

https://beta.boost.org/doc/libs/1_66_0/?view=condensed

**Comment by eldiener** [comment]
Looks good and is what I would like to see for the regular website also. Thanks !

**Comment by danieljames** [comment]
It's live now.
