### ISSUE TITLE
Consistently declare UTF-8 encoding if possible

### ISSUE THREAD

**Issue by CAM-Gerlach** [boostorg/website#334]
I happened to notice that ``Boost.org`` and ``beta.boost.org`` give somewhat contradictory encoding indications, and at odd with what I understand are modern best practices. 

For production ``boost.org``, the HTTP ``content-type`` header specifies ``charset=UTF-8``, while the HTML meta-tag ``contentt-type`` specifies ``charset=us-ascii``. As tested on a clean copy of Firefox [58, on Win 8.1 Pro x64], the assumed encoding is ``UTF-8``. On the other hand, ``beta.boost.org`` has no ``charset`` specified in the HTTP ``content-type`` header, while the HTML meta-tag ``content-type`` remained ``us-ascii``. Firefox thus assumes ``Windows-1252`` (!). (These were tested on both the main page and the website development page, with the same results).

Therefore, while I'm no expert, it would seem best to just declare ``UTF-8`` explicitly everywhere if possible, as is the modern best practice generally, and avoid any potential for trouble down the road. Unfortunately I've no experience with the particular static site generator ``boost.org`` uses, but I can't imagine it would be terribly complex to do unless there are other lingering encoding issues you all are aware of and I'm not (which may well be the case). Thanks!

**Comment by glenfe** [comment]
Fixed, I think.

**Comment by CAM-Gerlach** [comment]
LGTM. Thanks!
