### ISSUE TITLE
Missing image in documentation

### ISSUE THREAD

**Issue by PanderMusubi** [boostorg/website#361]
Online documentation for Boost is missing an image. See the screenshots below. Perhaps double check if this is also a missing image for older versions of Boost documentation and fix those too.

![2018-08-24-113715_1920x1080_scrot](https://user-images.githubusercontent.com/198964/44577883-813b2180-a792-11e8-834b-9280254400a4.png)

![2018-08-24-113717_1920x1080_scrot](https://user-images.githubusercontent.com/198964/44577885-813b2180-a792-11e8-96ac-b67b3fbec8c5.png)

**Comment by PanderMusubi** [comment]
Also other images such as the one in the footer are missing, see also https://www.boost.org/doc/libs/1_68_0/libs/doc/images/valid-html401.png

**Comment by PanderMusubi** [comment]
For old versions, those URLs could be fixed with rewrite rules in the web server.

**Comment by jwakely** [comment]
Maybe, but it's not important enough to bother IMHO.

**Comment by glenfe** [comment]
Fixed in Tokenizer for 1.70.
