### ISSUE TITLE
codestyle

### ISSUE THREAD

**Issue by ohhmm** [boostorg/website#392]
Please, create a webpage with descriptive common coding style guidelines.
Include there naming conventions.
Add rule that every name must have closest semantic meaning to its inner content in this set of libraries.

**Comment by mloskot** [comment]
The section [Requirements and guidelines](https://www.boost.org/development/index.html) includes guidelines for naming things like files or include guards, basic guidelines for design and how to integrate libraries with the Boost collection.

However, no common coding style guidelines for Boost libraries exists.

> Add rule that every name must have closest semantic meaning to its inner content in this set of libraries.

You will need to make your suggestion more concrete, a reviewable piece in context of existing guidelines and polices. Feel free to submit a PR (and re-open this issue).
