### ISSUE TITLE
 Boost.Build documentation link broken

### ISSUE THREAD

**Issue by Yanson32** [boostorg/website#451]
In the getting started section. There is a link to the [ boost build documentation](https://www.boost.org/doc/libs/1_71_0/more/getting_started/windows.html#invoke-b2) that is giving me a 404 file not found error.

**Comment by JGoldstone** [comment]
In fact there are many.

These are all on https://www.boost.org/doc/libs/1_71_0/more/getting_started/unix-variants.html. (The counterpart links on the comparable Windows page are also broken.)

The nonexistent page https://www.boost.org/doc/libs/1_71_0/tools/build/index.html is referenced in sections 5.2 ("Boost.build"), 5.2.1 ("Boost.build documentation"), 5.2.3 ("Boost.Build"), and 7 ("Boost.Build reference manual"). They all indirect to /home/www/shared/archives/live/boost_1_71_0/tools/build/index.html, which doesn't exist.

5.2.2's "in the Boost.Build Documentation" tries to take you to https://boostorg.github.io/build/doc/html/bbv2/reference/tools.html, which doesn't exist. That same nonexistent page is linked by 5.2.2's next sentence, in the Note, as the "building b2" link, and by 5.2.4's "Boost.Build documentation".

The "here" in the second sentence of 5.4 tries to take you to https://boostorg.github.io/build/doc/html/bbv2/overview/configuration.html, which doesn't exist.

These have been broken for some time (certainly in 1.70, not sure about 1.69); I would have spoken up sooner but didn't find this page until now.

**Comment by mloskot** [comment]
The related content lives in https://github.com/boostorg/boost/tree/master/more/getting_started, so the issue belongs in the superproject repo. It's been already reported there https://github.com/boostorg/boost/issues/293 Closing as dup
