### ISSUE TITLE
Download fails with "Forbidden"

### ISSUE THREAD

**Issue by maliberty** [boostorg/website#475]
On https://www.boost.org/users/download/#live the links to download all give 'Forbidden', eg https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2.

**Comment by tt4g** [comment]
I found same issue: boostorg/boost#299

**Comment by mclow** [comment]
I just tried it 6:45AM PST 2-Mar-2020 and it worked fine.

**Comment by maliberty** [comment]
It was down all weekend but came back on monday.
