### ISSUE TITLE
Dead link in getting started guide.

### ISSUE THREAD

**Issue by chris-stones** [boostorg/website#560]
Apologies if this is not the right place to report this.  

In section 5.2.4 of [Geting Started](https://www.boost.org/doc/libs/1_74_0/more/getting_started/windows.html)  
There is a dead link to [Boost.Build documentation.](https://www.boost.org/build/doc/html/bbv2/overview/invocation.html)

**Comment by DamianArado** [comment]
The correct link should be [this](https://github.com/boostorg/build)

**Comment by glenfe** [comment]
Fixed for 1.76
