### ISSUE TITLE
Collaboration/Communcation area of C++ Slack Workspace should be more prominent on the website

### ISSUE THREAD

**Issue by jenisys** [boostorg/website#579]
C++ Slack Workspace is for collaboration and communication within the community and interested users.
Currently, you need to perform archeology on the Boost website to find it mentioned somewhere (after some other boost library mentioned it). As far as I understand it, many (or several) boost libraries are using this C++ Slack Workspace.

**RELATED RESOURCE:** https://cppalliance.org/slack/

**FOUND WHERE:** Context of Beast Library changes on this page
* https://www.boost.org/users/history/version_1_70_0.html

**DESIRED CHANGE:**
Mention it near Wiki or Mailing List or on the FAQ page or community related resources.

**Comment by mloskot** [comment]
The Slack is (still) unofficial space, AFAIU, see https://github.com/boostorg/website/pull/465

**Comment by jenisys** [comment]
Thanks for the information.
Should I close this issue the (or leave it open as reminded) ?

**Comment by mloskot** [comment]
`¯\_(ツ)_/¯` perhaps status of the Slack has changed, will change, no idea - I'm not a decision maker here.

**Comment by glenfe** [comment]
As @mloskot said, the C++ Slack is not an official Boost discussion forum. It might be an official Beast forum, which is why the Beast documentation is free to link it.
