### ISSUE TITLE
Link to the github repo from boost.org

### ISSUE THREAD

**Issue by kallisti5** [boostorg/website#651]
boost.org is extremely frustrating.
Navigate to boost.org, and try to find the link to the github repositories.

It teases you link a lot of documentation on how git works, but never actually links you to the github repo.

**Comment by glenfe** [comment]
As per the  https://github.com/boostorg/website/issues/584#issuecomment-780807775 a website design is underway, but in the meanwhile perhaps the following change https://github.com/boostorg/website/commit/9d8efb04962c1a3e0d7dbbf5ee2e737b46a07bbf will do.
