### ISSUE TITLE
View as text on the wiki is broken

### ISSUE THREAD

**Issue by ned14** [boostorg/website#75]
To repeat:

1. Go to https://svn.boost.org/trac/boost/wiki/SoCSubmissionTemplate.

2. At the bottom of the page where it says "Download in other formats" choose "Plain text".

3. Witness the explosion:

The response from the server contained duplicate headers. This problem is generally the result of a misconfigured website or proxy. Only the website or proxy administrator can fix this issue.
Error code: ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

Niall

**Comment by danieljames** [comment]
Anything with the URL svn.boost.org is an issue for Trac.

**Comment by ned14** [comment]
Ah didn't know. Thanks.
