### ISSUE TITLE
No New/Updated libraries listed in News for Boost releases

### ISSUE THREAD

**Issue by Lastique** [boostorg/website#809]
Since Boost 1.83.0, the news entries on the front page (https://www.boost.org/) and News page (https://www.boost.org/users/news/) have empty "New libraries" and "Updated libraries" lists, although there are actually libraries in both categories. For example, in [1.83.0](https://www.boost.org/users/history/version_1_83_0.html), there is one new Compat library and 25 updated libraries in the release notes.

Boost 1.82.0 was the last release where the library lists were populated in the News.

**Comment by joaquintides** [comment]
The missing information has been provided [here](https://github.com/boostorg/website/pull/806) and [here](https://github.com/boostorg/website/pull/805), but it looks like boost.org needs be regenerated after this, @glenfe?

**Comment by glenfe** [comment]
Let me know if anything is still missing. (The above looks OK now).
