### ISSUE TITLE
Add testimonials to the Dawes memorial page

### ISSUE THREAD

**Issue by JonKalb** [boostorg/website#836]
The following testimonials were submitted (a long time ago), but never got added to the memorial page for Beman: https://www.boost.org/users/memoriam/beman_dawes.html

I think page has testimonials are sorted by last name.

Niall Douglas: Beman had an unusually large impact on C++ over his long and very productive life. My personal opinion of his most monumental achievement was getting Filesystem into standard C++, which was probably the most tortuous, lengthy, and difficult library to have ever been standardised (to date), and that followed a preceding tortuous, lengthy and difficult Boost peer review involving multiple redesigns of the proposed library. Beman was on WG21 from nearly the beginning, served as the Library Working Group chair for some time, and was one of the original cofounders of the Boost C++ Libraries. He also had a long history of continuous contributions to open source, starting from when many on r/cpp were still children.

Christopher Kormanyos: When the evolution from Fortran to C to C++ was on, progress seemed to hit a snag around the turn of the century. Beman's innovative, comprehensive and reliable work on C++ and Boost helped get C++ back on track. I feel that he enlightened the era and inspired other pioneers of that time and beyond, transforming C++ into the powerful, expressive language it is today.

David Sankel: I had the opportunity to interact with Beman at both BoostCon and the Standardization committee. He was an incredibly reasonable, and nurturing person. Boost and the greater C++ community is indebted to his tremendous legacy.

Andrey Semashev: Although I haven't known Beman in person, I feel in debt to him for his role in Boost and C++ in general. The Boost Project and the community around it were most educational and inspiring, which allowed me to grow as a developer over the years. His libraries, such as Boost.Filesystem and Boost.System, have helped countless users and made it into the C++ standard as fundamental library components. He has been a long member of the C++ Standards Committee and chaired the Library Working Group. One of the most influential people in the C++ world, he will be missed.

Bjarne Stroustrup and Herb Sutter: https://isocpp.org/blog/2020/12/remembering-beman-dawes

**Comment by glenfe** [comment]
Will be done in the new page.
